FROM jenkins:1.596
 
USER root
RUN apt-get update 
RUN apt-get install -y 
RUN rm -rf /var/lib/apt/lists/*
RUN echo "jenkins ALL=NOPASSWD: ALL" >> /etc/sudoers

USER jenkins
COPY plugins.txt /usr/share/jenkins/plugins.txt
RUN sudo /usr/local/bin/plugins.sh /usr/share/jenkins/plugins.txt

#EXPOSE 8080